# Generated by Django 2.1.3 on 2018-11-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='ciudad',
            field=models.CharField(max_length=50, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(max_length=50, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='profile',
            name='run',
            field=models.CharField(max_length=12, null=True, verbose_name='Rut'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tipo_vivienda',
            field=models.CharField(max_length=50, null=True, verbose_name='Tipo de Vivienda'),
        ),
    ]
