# Generated by Django 2.1.3 on 2018-11-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_contacto_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='Correo',
            field=models.EmailField(max_length=50),
        ),
    ]
