# Generated by Django 2.1.3 on 2018-11-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20181117_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='Perros'),
        ),
    ]
