# Generated by Django 2.1.3 on 2018-11-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20181117_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='Perros/'),
        ),
    ]
