# Generated by Django 2.1.3 on 2018-11-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20181130_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
